<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FbxControlNetConverter.Cli</RootNamespace>
    <AssemblyName>fbxcontrolnet</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\FbxControlNetConverter.Core.csproj" />
  </ItemGroup>

</Project>
